planManager/planManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name='main.html'), name='main'),
    path("admin/", admin.site.urls),
    path('', include("sign.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("creator-panel/", include('creatorPanel.urls')),
    path("student-panel/", include('studentPanel.urls')),
    path("profile-panel/", include('profilePanel.urls')),
    path("creator-panel/timetable", include('timetableWizard.urls')),
]

planManager/sign/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path("", TemplateView.as_view(template_name='main.html'), name='main'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

planManager/timetableWizard/models.py
from django.db import models

from creatorPanel.models import Group


class Timetable(models.Model):
    name = models.CharField(max_length=50)
    start = models.TimeField()
    duration = models.IntegerField()
    day_of_the_week = models.IntegerField()
    parity = models.BooleanField()
    instructor = models.CharField(max_length=30)
    classroom = models.CharField(max_length=20)
    group = models.ManyToManyField(Group)

planManager/planManager/templates/creator.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Creator page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/creator.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand">Creator panel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
                aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="/profile-panel">My account</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="mainBox">
    <div class="groupSection">
        <h2>Groups</h2>

        <table class="table table-bordered table-striped table-dark">
            <tr>
                <th>Name</th>
                <th>Show</th>
                <th>Add</th>
                <th>Remove</th>
                <th class="td-center">
                    <button id="myBtn" class="btn btn-sm btn-outline-light">Create Group</button>
                </th>
                <th class="td-center">
                    <button id="myBtn2" class="btn btn-sm btn-outline-light">Delete Group</button>
                </th>

            </tr>
            {% for obj in groups %}
            <tr>
                <td>{{obj.1}}</td>
                <td class="td-center">
                    <button name="{{obj.0}}" onclick="showStudents(this)" class="btn btn-sm btn-outline-info show-students-button"> Show Students</button>
                </td>
                <td class="td-center">
                    <button name="{{obj.0}}" onclick="addStudents(this)" class="btn btn-sm btn-outline-info add-students-button"> Add Students </button>
                </td>
                <td class="td-center">
                    <button name="{{obj.0}}" onclick="removeStudents(this)" class="btn btn-sm btn-outline-info remove-students-button"> Remove Students </button>
                </td>
                <td class="td-center">
                    <form method="POST" action="{% url 'timetableWizard' %}">
                        {% csrf_token %}
                        <input type="hidden" name="group_id" value="{{obj.0}}">
                        <button type="submit" class="btn btn-sm btn-outline-info create-plan-button"> Create Plan </button>
                    </form>
                </td>
            </tr>

            <div id="show-students-modal-{{obj.0}}" class="show-students-modal">
                <!-- Modal content -->
                <div class="modal-content">
                    <button name="{{obj.0}}" class="close" onclick="closeModal(this)">&times;</button>
                    <h2>Students List</h2>
                    {% for student in obj.2 %}
                    <b>{{student.2}}</b>
                    {% endfor %}
                </div>
            </div>

            <div id="remove-students-modal-{{obj.0}}" class="remove-students-modal">
                <!-- Modal content -->
                <div class="modal-content">
                    <button name="{{obj.0}}" class="close" onclick="removeStudentsCloseModal(this)">&times;</button>
                    <h2>Select students to remove</h2>
                    <form method="POST" action="{% url 'removeStudent' %}" class="saveNoteForm">
                        {% csrf_token %}
                        <fieldset>
                        {% for student in obj.2 %}
                            <div>
                                <input type="checkbox" value="{{student}}" name="studentsToBeRemoved" >{{student.2}}<br>
                            </div>
                        {% endfor %}
                            <button type="submit">Remove</button>
                        </fieldset>
                    </form>
                </div>
            </div>

            <div id="add-students-modal-{{obj.0}}" class="add-students-modal">
                <!-- Modal content -->
                <div class="modal-content">
                    <button name="{{obj.0}}" class="close" onclick="addStudentsCloseModal(this)">&times;</button>
                    <h2>Select students to add</h2>
                    <form method="POST" action="{% url 'addStudent' %}" class="saveNoteForm">
                        {% csrf_token %}
                        <fieldset>
                        {% for student in obj.3 %}
                            <div>
                                <input type="checkbox" value="{{student}}" name="studentsToBeAdded" >{{student.2}}<br>
                            </div>
                        {% endfor %}
                            <button type="submit">Add</button>
                        </fieldset>
                    </form>
                </div>
            </div>
            {% endfor %}

        </table>
        <div class="studentSection">
            <h2>Students</h2>
            <table class="table table-bordered table-striped table-dark">
                <tr>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th>Email</th>
                    <th></th>
                </tr>
                {% for obj in groupsOfStudent %}
                <tr>
                    <td>{{obj.1}}</td>
                    <td>{{obj.2}}</td>
                    <td>{{obj.3}}</td>
                    <td class="td-center">
                        <button name="{{obj.0}}" onclick="showGroups(this)" class="btn btn-sm btn-outline-info show-groups-button"> Show Groups</button>
                    </td>
                </tr>

                <div id="show-groups-modal-{{obj.0}}" class="show-groups-modal">

                    <!-- Modal content -->
                    <div class="modal-content">
                        <button name="{{obj.0}}" class="close" onclick="closeModal3(this)">&times;</button>
                        <h2>Groups List</h2>
                        {% for obj in obj.4 %}
                            <b>{{obj}}</b>
                        {% endfor %}
                    </div>

                </div>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

<div id="create-group-modal" class="modal">
    <div class="modal-content">
        <button name="{{obj.0}}" class="close" onclick="closeModal2(this)">&times;</button>
        <form method="POST" action="{% url 'saveGroup' %}" class="saveNoteForm">
            {% csrf_token %}
            <h2>Create Group</h2>
            <textarea class="noteTextArea" placeholder="Group name" name="group" required="" id="id_textarea"></textarea>
            <input type="submit" value="Save" class="saveSubmit">
        </form>
    </div>
</div>

<div id="delete-group-modal" class="modal">
    <div class="modal-content">
        <button name="{{obj.0}}" class="close" onclick="deleteGroupCloseModal(this)">&times;</button>
        <h2>Select group to delete</h2>
        <form method="POST" action="{% url 'deleteGroup' %}" class="saveNoteForm">
            {% csrf_token %}
            <fieldset>
            {% for group in groups %}
                <div>
                    <input type="checkbox" value="{{group.0}}" name="groupsToBeDeleted" >{{group.1}}<br>
                </div>
            {% endfor %}
                <button type="submit">Delete</button>
            </fieldset>
        </form>
    </div>
</div>

<script>

function showStudents(element) {
    var id = "show-students-modal-" + element.name;
    console.log(id);
    var modal = document.getElementById(id);
    modal.style.display = "block";
}

function showGroups(element) {
    var id = "show-groups-modal-" + element.name;
    console.log(id);
    var modal = document.getElementById(id);
    modal.style.display = "block";
}

function removeStudents(element) {
    var id = "remove-students-modal-" + element.name;
    console.log(id);
    var modal = document.getElementById(id);
    modal.style.display = "block";
}

function addStudents(element) {
    var id = "add-students-modal-" + element.name;
    console.log(id);
    var modal = document.getElementById(id);
    modal.style.display = "block";
}

function closeModal(element) {
    var id = "show-students-modal-" + element.name;
    console.log(id);
    var modal = document.getElementById(id);
    modal.style.display = "none";
}

function removeStudentsCloseModal(element) {
    var id = "remove-students-modal-" + element.name;
    console.log(id);
    var modal = document.getElementById(id);
    modal.style.display = "none";
}

function addStudentsCloseModal(element) {
    var id = "add-students-modal-" + element.name;
    console.log(id);
    var modal = document.getElementById(id);
    modal.style.display = "none";
}

function deleteGroupCloseModal(element) {
    var modal = document.getElementById("delete-group-modal");
    modal.style.display = "none";
}

function closeModal2(element) {
    var modal = document.getElementById("create-group-modal");
     modal.style.display = "none";
}

function closeModal3(element) {
    var id = "show-groups-modal-" + element.name;
    console.log(id);
    var modal = document.getElementById(id);
    modal.style.display = "none";
}

var btn = document.getElementById("myBtn");
var btn2 = document.getElementById("myBtn2");

var modal = document.getElementById("create-group-modal");
var deleteModal = document.getElementById("delete-group-modal");
var showStudentsButtons = document.querySelectorAll(".show-students-button");
var addStudentsButtons = document.querySelectorAll(".add-students-button");
var showGroupsButtons = document.querySelectorAll(".show-groups-button");
var removeStudentsButtons = document.querySelectorAll(".remove-students-button");
var addStudentsButtons = document.querySelectorAll(".add-students-button");

btn.onclick = function() {
  modal.style.display = "block";
}

btn2.onclick = function() {
  deleteModal.style.display = "block";
}
</script>

</body>
</html>

planManager/planManager/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Plan Manager - Main Page</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/general.css' %}">
    </head>
<body>
    <div class="mainBox">
        <h1>Plan Manager</h1>
        <ul>
            <li><a href="/student-panel">Student Panel</a></li>
            <li><a href="/creator-panel">Creator Panel</a></li>
            <li><a href="/admin">Admin Panel</a></li>
        </ul>
    </div>
</body>
</html>

planManager/planManager/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Profile Manager - {{ user.username }}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/general.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand">Profile Panel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
                aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="#">My account</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="mainBox">
    <h1>User Information</h1>
    <table class="table table-bordered table-striped table-dark">
        <tr>
            <td>Username</td>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <td>Firstname</td>
            <td>{{ user.first_name }}</td>
        </tr>
        <tr>
            <td>Lastname</td>
            <td>{{ user.last_name }}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{ user.email }}</td>
        </tr>
    </table>
    <h1>{{ user.username }}'s saved notes</h1>
    <table class="table table-bordered table-striped table-dark">
        {% for obj in query %}
        <tr>
            <td>{{obj.0}}</td>
        </tr>
        {% endfor %}
    </table>
    <!-- url 'saveNote'-->
    <form method="POST" action="{% url 'saveNote' %}" class="saveNoteForm">
        {% csrf_token %}
        <h2>Save your private notes</h2>
        <textarea class="noteTextArea" placeholder="Note" name="note" required="" id="id_textarea">
                </textarea>
        <input type="submit" value="Save" class="saveSubmit">
    </form>
</div>
</body>
</html>

planManager/planManager/templates/student.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/student.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand">Student panel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
                aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="/profile-panel">My account</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="mainBox">
    <div class="timetableSection">
        <h2>My timetable</h2>

        <table class="table table-bordered table-striped table-dark">
            <tr>
                <th>Name</th>
                <th>Start</th>
                <th>Duration (in minutes)</th>
                <th>Day of the week</th>
                <th>Week's parity</th>
                <th>Instructor</th>
                <th>Classroom</th>
            </tr>
            {% for obj in timetables %}
            <tr>
                <td>{{obj.1}}</td>
                <td>{{obj.2}}</td>
                <td>{{obj.3}}</td>
                <td>{{obj.4}}</td>
                <td>{{obj.5}}</td>
                <td>{{obj.6}}</td>
                <td>{{obj.7}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
</body>
</html>

planManager/planManager/templates/timetable.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit timetable</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/creator.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand">Editing timetable for group {{group_name}}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
                aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="/profile-panel">My account</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="mainBox">
    <div class="lessonsSection">
        <h2>Add lesson</h2>

        <form method="POST" action="{% url 'addLesson' %}">
            <table class="table table-bordered table-striped table-dark">
                <tr>
                    <th>Name</th>
                    <th>Start</th>
                    <th>Duration (in minutes)</th>
                    <th>Day of the week</th>
                    <th>Week's parity</th>
                    <th>Instructor</th>
                    <th>Classroom</th>
                    <th></th>
                </tr>
                <tr>
                    <td>
                        <input class="inputtext" type="text" id="id_name" name="name" maxlength="50" size="30" required>
                    </td>
                    <td>
                        <input class="inputtext" type="time" id="id_timestart" name="starttime" min="6:00" max="22:00" required>
                    </td>
                    <td>
                        <input class="inputtext inputnumber" type="number" id="id_duration" name="duration" min="30" max="600" value="90" required>
                    </td>
                    <td>
                        <select id="id_dayoftheweek" name="dayoftheweek">
                            <option value="0">Monday</option>
                            <option value="1">Tuesday</option>
                            <option value="2">Wednesday</option>
                            <option value="3">Thursday</option>
                            <option value="4">Friday</option>
                            <option value="5">Saturday</option>
                            <option value="6">Sunday</option>
                        </select>
                    </td>
                    <td>
                        <input class="inputtext" type="radio" id="id_odd" name="parity" value="odd" checked>
                        <label for="id_odd">Odd</label>
                        <input class="inputtext" type="radio" id="id_even" name="parity" value="even">
                        <label for="id_even">Even</label>
                    </td>
                    <td>
                        <input class="inputtext" type="text" id="id_instructor" name="instructor" maxlength="30" required>
                    </td>
                    <td>
                        <input class="inputtext" type="text" id="id_classroom" name="classroom" maxlength="20" required>
                    </td>
                    <td class="td-center">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-outline-info add-lesson-button"> Add Lesson </button>
                    </td>
                </tr>
            </table>
        </form>


        <h2>Current lessons</h2>

        <table class="table table-bordered table-striped table-dark">
            <tr>
                <th>Name</th>
                <th>Start</th>
                <th>Duration (in minutes)</th>
                <th>Day of the week</th>
                <th>Week's parity</th>
                <th>Instructor</th>
                <th>Classroom</th>
                <th></th>
            </tr>
            {% for obj in timetables %}
            <tr>
                <td>{{obj.1}}</td>
                <td>{{obj.2}}</td>
                <td>{{obj.3}}</td>
                <td>{{obj.4}}</td>
                <td>{{obj.5}}</td>
                <td>{{obj.6}}</td>
                <td>{{obj.7}}</td>
                <td class="td-center">
                    <form method="POST" action="{% url 'delLesson' %}">
                        {% csrf_token %}
                        <input type="hidden" name="lesson_id" value="{{obj.0}}">
                        <button type="submit" class="btn btn-sm btn-outline-info remove-lesson-button"> Remove Lesson </button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
</body>
</html>